compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: "./starVLA/config/deepseeds/zero3.yaml"
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED